spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

    druid:

      stat-view-servlet: #配置监控页按钮
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter: #监控web应用
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.atguigu.sbootweb02.*  #监控SpringBean

      filters: stat,wall   #底层开启功能，stat（sql监控），wall（防火墙）

      filter:
        stat: #对上面filters里面的stat精选详细设置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

#配置mybatis规则
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# management 是所有actuator的配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点